source 'https://rubygems.org'
# ruby '2.2.2'

gem 'rake'
gem 'rb-readline'

gem 'ruboty'
gem 'ruboty-alias'
# gem 'ruboty-bundler'
gem 'ruboty-cron'
gem 'ruboty-docker', path: 'vendor/gems/ruboty-docker'
gem 'ruboty-echo'
# gem 'ruboty-github'
gem 'ruboty-google_image'
gem 'ruboty-redis'
gem 'ruboty-replace'
gem 'ruboty-response'
gem 'ruboty-rss'
gem 'ruboty-ruby'
gem 'ruboty-slack'
gem 'ruboty-talk'
gem 'ruboty-twitter_search'

gem 'codeclimate-test-reporter', group: :test, require: nil
gem 'rspec'
